### ISSUE TITLE
django-extensions version 1.5.0

### ISSUE THREAD

**Issue by astamminger** [conda-forge/django-extensions-feedstock#32]
Hi @ocefpaf @kwilcox,

I would like to add django-extensions 1.5.0 to the feedstock. Could you tell me where I should push the recipe to? 

Best,
Andreas

**Comment by ocefpaf** [comment]
Just send a PR targeting `master` and I can create a branch for it later.

**Comment by astamminger** [comment]
Perfekt, thanks :)
